### ISSUE TITLE
Bug List Post

### ISSUE THREAD

**Issue by HieuQB** [vthhanh96/MXH_GiaoThong#10]
- [x] Trang trí lại nút Like, Dislike

- [x] Hiển thị thêm số lượt bình luận

- [x] Tạo thêm trang Detail Post (Nếu được)

- [x] Kiểm tra lại lỗi văng app khi vào chỉnh sửa post hoặc thêm post

- [x] Thêm Dialog Hỏi trước  khi xóa bài viết

- [x] Khi lọc không có kết quả thì nên thông báo gì đó cho người dùng biết.(Dạng text lên màn hình hoặc show toast)

- [x] Khi không có user đăng nhập, thì ấn được nút like, dislike liên tục không ngừng nghỉ

- [x] Khi lọc thành công -> sau đó muốn quay về trạng thái ban đầu thì không biết làm như thế nào cả?

**Comment by vthhanh96** [comment]
>  Kiểm tra lại lỗi văng app khi vào chỉnh sửa post hoặc thêm post

Sẽ fix sau

**Comment by HieuQB** [comment]
oke
