### ISSUE TITLE
Menu khi chưa đăng nhập

### ISSUE THREAD

**Issue by vthhanh96** [vthhanh96/MXH_GiaoThong#11]
- [x]  Khi không đăng nhập nên để để avatar mặc định, remove name và email

- [x]  Nút đăng xuất chuyển lại thành đăng nhập và khi ấn vào ra màn hình login

- [x]  Đồng thời chặn lại việc user nhấn vào avatar hiện màn hình profile

![screenshot_1527741288](https://user-images.githubusercontent.com/19782537/40761721-07169df2-64c7-11e8-8907-48fbd928348d.png)

**Comment by vthhanh96** [comment]
- [ ]  Sau khi đăng xuất ra bấm vào menu bị lag

![ezgif com-optimize](https://user-images.githubusercontent.com/19782537/40817956-fd46e71a-657e-11e8-8847-53faf75ffb88.gif)

**Comment by HieuQB** [comment]
căng vậy :D

**Comment by vthhanh96** [comment]
bên ông có bị lag ko chứ t thấy lag lắm ak. Mà nếu t có đăng nhập thì nó lại ko bị lag

**Comment by HieuQB** [comment]
Ý bên t bình thường á
